### ISSUE TITLE
Enable/Disable Audio Video and Share Screen of Other User

### ISSUE THREAD

**Issue by pawanlakhera77** [aws/amazon-chime-sdk-component-library-react#260]
I was implementing a class where students can join along with teacher and teacher has full access to allow student to speak and show their video whenever she likes.

I was implementing this feature using React SDK library but I do not found any Documentation where it is explained that how we can enable/disable the student(attendee) video from the Teachers account.

Is this currently possible in React SDK to implement this feature?

**Comment by devalevenkatesh** [comment]
Hello @pawanlakhera77 ,

This component library is based on [`amazon-chime-sdk-js`](https://github.com/aws/amazon-chime-sdk-js) which handles the audio, video and content share. 

Since the `amazon-chime-sdk-js` library does not yet support remote attendee audio, video and content share enabling / disabling, we do not have any functionality around it in the component library yet.

You can use [Amazon Chime JS SDK's Data Messages APIs](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional) to implement your feature. Please check links below which may help further:
1. [FAQ - Does the SDK support remote mute where one attendee can mute another?
](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#does-the-sdk-support-remote-mute-where-one-attendee-can-mute-another)

2. [Mute Remote Attendee](https://github.com/aws/amazon-chime-sdk-js/issues/237) issue in `amazon-chime-sdk-js`.

We will update the documentation once the UI and SDK components related to remote attendee audio, video and content share become available. Closing the issue.
