### ISSUE TITLE
Not Connected error occurs after joined a meeting for 30 mins ~1 hour

### ISSUE THREAD

**Issue by Sujin1135** [aws/amazon-chime-sdk-component-library-react#403]
**Describe the bug**
Not Connected error occurs after joined a meeting with video / audio turned off
How can I solve it?

**To Reproduce**
1. Join a meeting
2. Turn off audio / video
3. Keep joining

**Expected behavior**
I want to keep to connect a session

**Screenshots**
![이미지 2](https://user-images.githubusercontent.com/25698674/106552720-2c9f5180-655b-11eb-8748-e2d287669aa8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 87.0.4280.141
 - 
**Additional context**
Actually, I've tried to relay a chime meeting refer to https://github.com/aws-samples/amazon-chime-sdk-recording-demo,
However, It was disconnected after 30 mins ~ 1 hour. I couldn't find what caused it. I wanna solve it.

**Comment by simmkyu** [comment]
Your logs indicate that your Chime SDK meeting ended with the `AudioCallEnded` status code ([Click here to see the API doc](https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html#audiocallended)).

A Chime SDK meeting automatically ends after a period of inactivity to ensure that the customer is not overcharged accidentally. From https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html
- No audio connections are present in the meeting for more than five minutes.
- Less than two audio connections are present in the meeting for more than 30 minutes.
- Screen share viewer connections are inactive for more than 30 minutes.
- The meeting time exceeds 24 hours.

Your meeting seemed to end due to the second case:
> Less than two audio connections are present in the meeting for more than 30 minutes.

Ensure that two or more attendees join a meeting if you want to continue your session. Please reopen if you have any questions.

**Comment by 3ating** [comment]
@simmkyu I just found some rules on this [page](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-mtgs.html), but I couldn't find information about "Less than two audio connections are present in the meeting for more than 30 minutes" in https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html. I want to know whether the documentation was not written, or if I looked in the wrong place. Thanks!
