### ISSUE TITLE
[MeetingManager audioVideoDidStop] session stopped with code 12

### ISSUE THREAD

**Issue by vinuv00702** [aws/amazon-chime-sdk-component-library-react#553]
Created meeting and the reponse is passed into meetingmanager. The device setup works fine as it shows my audio video devices and able to choose from the list. But whwn i click join meeting, ie when **meetingManager.start();** is called the meeting screen is showed for a couple of seconds and then the meeting ends. The following error shows in the console **[MeetingManager audioVideoDidStop] session stopped with code 12**. When I looked up about it, most suggestions were saying that it occured when trying to join a deleted meeting. But my meeting is created just at the moment and I can't find the issue. I hope somebody could help
![chime _errr](https://user-images.githubusercontent.com/58970601/124709612-4df4d700-df19-11eb-9bfd-ff50242db3ba.jpg)
![chime _errr0](https://user-images.githubusercontent.com/58970601/124709619-4f260400-df19-11eb-85da-865b0c6c36fc.jpg)

**Comment by michhyun1** [comment]
Please refer to the documentation here: https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html#signalingbadrequest

The meeting session Status code is 12: Signaling Bad Request.

**Comment by vinuv00702** [comment]
> Please refer to the documentation here: https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html#signalingbadrequest
> 
> The meeting session Status code is 12: Signaling Bad Request. Let me know if that helps you out.

**Comment by michhyun1** [comment]
@vinuv00702 Did that reply help? Should I close this issue now?

**Comment by vinuv00702** [comment]
> @vinuv00702 Did that reply help? Should I close this issue now?

No, the issue is still there. The document says error code 12 is signaling bad request which arises when the meeting is already deleted or so . But nothing such is done in my project. It happens when i try join the meeting which created at that exact moment.

But today i found that my device status is always UNSET even after i give permission. Would that be the issue?.. found similar issue reported here and some actually said about not being able to join the meeting..

**Comment by xuesichao** [comment]
Hi @vinuv00702 
>But today i found that my device status is always UNSET even after i give permission. Would that be the issue?

I assume you are referring to `useDevicePermissionStatus` hook. Your issue seems not relate to this hook.

This hook works only when the device permission status is unset. **This hook is not aimed to detect the device permission of the browser.** It is always `UNSET` when user opens the application (check the code here [useDevicePermissionStatus.tsx#L12](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/dfe904fec85b5f7c21af690e37c32e4806320e81/src/hooks/sdk/useDevicePermissionStatus.tsx#L12)). 

The purpose of this hook is to allow builder to customize UI when device permission prompt is triggered. For example, if you want to pop up a dialog when the device permission prompt is triggered to warn the user that they need to allow the permission or the application may not work properly.

Currently there isn't a one-for-all solution to get the correct device permission status from the browsers. We will improve it once the browsers support such kind of [query function](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query).
