### ISSUE TITLE
roster is empty sometimes?

### ISSUE THREAD

**Issue by subhendukundu** [aws/amazon-chime-sdk-component-library-react#558]
While using `useRosterState` I see roster  is empty sometimes.
```
const { roster } = useRosterState();
 const attendees = Object.values(roster);
```
 But the `attendeeIdToTileId ` has the right details. `const { attendeeIdToTileId } = useRemoteVideoTileState();`
 I am not able to reproduce when is that happening exactly, but I see it empty sometimes. What could be the reason? Is there a way I can make sure, it is not empty.
 
 Using it like
 ```
// userCreatedRoom.jsx not root
 <MeetingProvider>
      <div className={classes.root}>
        <UserActivityProvider>
          <MeetingView
            id={id}
          />
        </UserActivityProvider>
      </div>
    </MeetingProvider>
 ```
 then in `MeetingView`
 ```
export default function MeetingView({
  id,
}) {
  const meetingManager = useMeetingManager();
  const meetingStatus = useMeetingStatus();
  const audioVideo = useAudioVideo();
  const { attendeeIdToTileId } = useRemoteVideoTileState();
  const { roster } = useRosterState();
  const attendees = Object.values(roster);
  console.log('attendees', attendees); // empty array

useEffect(() => {
    join(); // calls meetingManager.join() and start()
    return () => {
      console.log('closing meeting for', id);
      meetingManager.leave();
    };
  }, [id]);

return(
<NiceUI />
);
}
 ```

**Comment by michhyun1** [comment]
@subhendukundu Thanks for using the Chime SDK React Component Library! Can you give more context as to when the roster state returns empty? I see that you join the meeting in the useEffect hook - perhaps you can try joining the meeting before printing out the roster. Thanks

**Comment by subhendukundu** [comment]
Not exactly sure when it is. I have moved my code to `amazon-chime-sdk-js` directly and it is working. Probably an integration issue. I would still leave the whole code here just FYI. Maybe you would see the issue (if any) and so that it helps to improve the library.

```
// App.js
<Router>
  <Switch>
      <Route exact path="/">
        <HomePage />
      </Route>
      <Route exact path="/events/:id">
        <ViewOnlyVideoCalls />
      </Route>
     // Other routes which doesn't need Chime
  </Switch>
</Router>
 ```

// ViewOnlyVideoCalls.js
```
import React, { memo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  UserActivityProvider,
  MeetingProvider,
} from 'amazon-chime-sdk-component-library-react';
import Box from '@material-ui/core/Box';
import CircularProgress from '@material-ui/core/CircularProgress';
import { useSubscription } from '@apollo/client';
import { MEETING_BY_ID } from '../../../graphql/subscription';
import { useParams } from 'react-router-dom';
import { makeStyles } from '@material-ui/styles';

import BroadcastView from './components/BroadcastView';

interface Props {}

const useStyles = makeStyles(theme => ({
  root: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    height: '100%',
    '& >div': {
      display: 'flex',
      flex: 1,
      flexDirection: 'column',
    },
  },
  ivsWrapper: {
    position: 'absolute',
  },
}));
interface Params {
  id: string;
  room: string;
}

export const ViewOnlyVideoCalls = memo((props: Props) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { t, i18n } = useTranslation();
  const params = useParams<Params>();
  const { id } = params;
  const classes = useStyles();
  const { loading, error, data = {} } = useSubscription(CALL_BY_ID, {
    variables: { id },
  });

  if (loading) {
    return (
      <Box
        flex={1}
        display="flex"
        alignItems="center"
        justifyContent="center"
        flexDirection="column"
        height="100%"
      >
        <Box marginBottom="10px">{t('rooms.loading')}</Box>
        <CircularProgress color="inherit" />
      </Box>
    );
  }

  return (
    <MeetingProvider>
      <div className={classes.root}>
        <UserActivityProvider>
          <CallView
            id={id}
          />
        </UserActivityProvider>
      </div>
    </MeetingProvider>
  );
});
```
```
//CallView.js
import React, { useCallback, useEffect } from 'react';
import {
  RemoteVideo,
  VideoTileGrid,
  useMeetingManager,
  DeviceLabels,
  useAudioVideo,
  useRemoteVideoTileState,
  useMeetingStatus,
  MeetingStatus,
  useRosterState,
} from 'amazon-chime-sdk-component-library-react';
import Box from '@material-ui/core/Box';
import { useMutation } from '@apollo/client';
import { GET_ATTENDEE_MEETING_INFO } from 'graphql/mutation';
import { useDispatch } from 'react-redux';
import { useUserSlice } from 'app/pages/RouterPage/slice';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles(theme => ({
  root: {
    position: 'relative',
    gridArea: 'content',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  videos: {
    flex: 1,
    height: '100%',
    background: 'transparent',
  },
  hide: {
    display: 'none',
  },
}));

function getRandomUserId() {
  // loging returning id
  return id;
}

export default function CallView({ id }) {
  const meetingManager = useMeetingManager();
  const meetingStatus = useMeetingStatus();
  const audioVideo = useAudioVideo();
  const [getMeetingAttendeeInfo] = useMutation(GET_ATTENDEE_MEETING_INFO);
  const dispatch = useDispatch();
  const { actions } = useUserSlice();
  const classes = useStyles();
  const { attendeeIdToTileId } = useRemoteVideoTileState();
  const { roster } = useRosterState();
  const attendees = Object.values(roster);
  console.log('attendees', attendees);
  const userShowingNow = attendees.find(
    item => item.externalUserId === getRandomUserId() || '',
  );

  const join = useCallback(async () => {
    dispatch(actions.setLoader(true));
    const response = await getMeetingAttendeeInfo({
      variables: {
        object: {
          user_id: id,
          room_id: id,
        },
      },
    });
    const {
      data: { user },
    } = response;
    if (user.MeetingInfo && user.AttendeeInfo) {
      const joinData = {
        meetingInfo: user.MeetingInfo,
        attendeeInfo: user.AttendeeInfo,
        deviceLabels: DeviceLabels.None,
      };

      await meetingManager.join(joinData);
      await meetingManager.start();
    }
    dispatch(actions.setLoader(false));
  }, [id]);

  useEffect(() => {
    if (meetingStatus === MeetingStatus.Ended) {
      console.log('[useEffect] Meeting ended');
      join();
    }
  }, [join, meetingStatus]);

  useEffect(() => {
    join();
    return () => {
      console.log('closing meeting for', id);
      meetingManager.leave();
    };
  }, [id]);

  console.log('attendeeIdToTileId', attendeeIdToTileId);
  console.log('userShowingNow', userShowingNow);
  return (
    <Box display="flex" flexDirection="column" flex={1}>
      <RemoteVideo
        tileId={attendeeIdToTileId[userShowingNow?.chimeAttendeeId]}
      />
    </Box>
  );
}

```

**Comment by simmkyu** [comment]
The **Building a Roster** section in the [SDK Hooks guide](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-hooks-introduction--page) says the following:

> Note - You will need to have provided meetingManager.getAttendee with a function to fetch your attendee names, otherwise there will be no names in the roster.

Could you ensure that you implement the `meetingManager.getAttendee` method to return an attendee object? See the following guide for the `meetingManager.getAttendee` description.
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-meetingmanager--page


Also, note that the `meetingManager.getAttendee` returns a promise: `Promise<AttendeeResponse>`. When you first join a meeting, the `useRosterState` returns an empty object. Once your app successfully fetches and resolves the promise with an attendee, the `useRosterState` will return an attendee object.

**Comment by subhendukundu** [comment]
So you are saying we need to add `meetingManager.getAttendee`? ATM we arent using this at all. Then `meetingManager.getAttendee` should be must when you are using `useRosterState`.

**Comment by subhendukundu** [comment]
@ltrung Any idea on this one?
When I join from landing page to meeting room we get the right info.
But when we refresh the meeting room we get inconsistent info.
`console.log('attendeeIdToTileId, roster', attendeeIdToTileId, roster);` prints `attendeeIdToTileId, roster {199ef373-a135-d5ef-8dd7-67bc637c097c: 1} {}`
Means, `attendeeIdToTileId` has the right info while `roster` is empty. So weird. :(

**Comment by subhendukundu** [comment]
Same behaviour for a small minimal app I have created. https://github.com/subhendukundu/aws-chime-content-share

inconsistency with`useRemoteVideoTileState` and `useRosterState`

**Comment by michhyun1** [comment]
@subhendukundu Perhaps you can take a look at the meeting demo: https://github.com/aws-samples/amazon-chime-sdk/blob/299d0401e28e84b3a60ecaa97ba26a23ded27a1d/apps/meeting/src/containers/MeetingForm/index.tsx#L67

The callback is defined here: https://github.com/aws-samples/amazon-chime-sdk/blob/299d0401e28e84b3a60ecaa97ba26a23ded27a1d/apps/meeting/src/utils/api.ts#L39

Please take a look and let us know if that answers your question.

**Comment by devalevenkatesh** [comment]
Hi @subhendukundu ,

The roster is initialized to `{}` when the `RosterProvider` is re-mounted or un-mounted (check [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/RosterProvider/index.tsx#L88-L92)) and hence the state you are seeing is `{}`.

The library currently does not do any state management to maintain app-refreshes (browser window refreshes). The `RosterProvider` is dependent on the `realtimeSubscribeToAttendeeIdPresence` API from Amazon Chime SDK for JavaScript, which we un-subscribe while un-mounting and subscribe while mounting if a valid `audioVideo` object is present from the `meetingSession` created in the `MeetingManager` when you call `join` and then `start` on `meetingManager` from `useMeetingManager`. So, on browser window refresh, since, no attendee would be present as there is no re-joining taking place in the `meetingManager` upon browser window refresh, the roster state will be `{}` as expected.

Now, I am a bit confused on the `useRemoteVideoTileState` issue. The roster management is audio driven and the `RemoteVideoTileProvider` which provides the remote video tile state using `useRemoteVideoTileState` is `videoTileDidUpdate` and `videoTileDidRemoved` driven. We do reset the state (check [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/RemoteVideoTileProvider/index.tsx#L58)) when the component un-mounts and hence the map `attendeeIdToTileId` should be getting cleared as well. I suspect in your case, since the `audioVideo` object is not valid hence upon window refresh, this RESET never runs and hence the mismatch in state. Can you please add a breakpoint and see if the RESET action is triggered?

I tested this by joining a meeting and leaving the meeting in our [react meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) and it worked as expected and went through the RESET flow. Unfortunately, as mentioned we do not support browser window refresh and I could not test it as our meeting demo is not setup to handle such use-case.

I tried to check your minimal app but I could not run it due to multiple errors. To debug this further, could you please add an updated README in your minimal app with repro steps? Also, it would be great if you could remove any components that are un-related to this issue to make this a small repro demo.
