### ISSUE TITLE
PreviewVideo triggers isLocalVideo on on v2.15.0

### ISSUE THREAD

**Issue by jherrera-bcov** [aws/amazon-chime-sdk-component-library-react#752]
### What happened and what did you expect to happen?

When enabling PreviewVideo, the `isVideoEnabled` value is being returned as `true`. 
According to the [docs](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-hooks-uselocalvideo--page) enabling PreviewVideo should not modify this value.

The application uses RemoteVideo, and it is being turned on (only a black screen) when PreviewVideo is enabled

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Enable/ render PreviewVideo
2. `isLocalVideo` value will be true
3. RemoteVideo that was previously off, will turn on and a black screen will be displayed

### Amazon Chime SDK React Components Library version

2.15.0

### What browsers are you seeing the problem on?

Edge

### Browser version

96.0.1054.62

### Device Information

macOS 10.15.7

### Meeting and Attendee ID Information.

Meeting ID: room_08_mar_10.00
Attendee ID: b19fc361-c42c-83e3-4310-12b0d7f7c10d

### Browser console logs

None

**Comment by nainkunal933** [comment]
Hey @jherrera-bcov,

Thank you for opening this issue. I went through the documentation and could not find the documentation which implied this:
> According to the [docs](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-hooks-uselocalvideo--page) enabling PreviewVideo should not modify this value.

Can you please send me the excerpt of the text which says that?

Also, I would like to know are `PreviewVideo` and `LocalVideo` components rendered on the same page in your application?
Console logs for the black screen behavior would be great.

**Comment by jherrera-bcov** [comment]
HI @nainkunal933 
Here's the text:, I assumed that having `PreviewVideo` enabled does not change `isVideoEnabled`
> // Whether or not the local user has video enabled
  // This does not tell whether the video preview from `PreviewVideo` component is enabled or not.
  isVideoEnabled: boolean;
  
 `PreviewVideo` and `RemoteVideo` are being rendered in the same page. Previously, we could open the modal containing the preview video and the main video (Remote) would not be turned off. It did turn off when closing the `PreviewVideo`, that is expected. 
This new behavior, where opening the modal that renders `PreviewVideo ` triggers `isLocalVideo`  and enables the `RemoteVideo` in the same page, is not expected.

**Comment by jkelting** [comment]
I have seen the same thing, which changed when I updated to the latest sdk and component version.

**Comment by nainkunal933** [comment]
@jherrera-bcov, thank you for providing the requested info. So, there are a couple of things going on here.

> I assumed that having PreviewVideo enabled does not change isVideoEnabled

I am sorry for this confusion but as you can see from the implementation of `PreviewVideo` component, `isVideoEnabled` value is getting updated: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/components/sdk/PreviewVideo/index.tsx#L47. So, that answers the first question. 

I can see why the documentation can be confusing. I think the culprit in documentation is the following statement.
> This does not tell whether the video preview from PreviewVideo component is enabled or not.

I believe this statement was true earlier but overtime updates to `PreviewVideo` have created a tight coupling between `PreviewVideo` and `isVideoEnabled`. This PR is late 2021 have added that coupling completely: https://github.com/aws/amazon-chime-sdk-component-library-react/commit/70199152f984b9d2d983e375361173b5a25e1b3e#diff-80ef89bc050d17d5ccf5109f3f22a2ad1eae42504e2a0ed8e4a8613593811664R63. As an action item, I can remove that sentence from the documentation. 

Now, to the second part of your question, I do not understand how the following scenario is possible.
> This new behavior, where opening the modal that renders PreviewVideo triggers isLocalVideo and enables the RemoteVideo in the same page

 It seems like your application is currently using `PreviewVideo` and `RemoteVideo` in the same page. `PreviewVideo` will update `isVideoEnabled` property and that might affect `LocalVideo` but I could not find any correlation between `isVideoEnabled` and `RemoteVideo`. Can you please share your application console logs so that I can take a look?

**Comment by nainkunal933** [comment]
@jherrera-bcov I created a demo application where the `PreviewVideo` component was rendered on the same as the `RemoteVideo` component and I could not reproduce the behavior that you mentioned.
> This new behavior, where opening the modal that renders PreviewVideo triggers isLocalVideo and enables the RemoteVideo in the same page

Can you please send me a code snippet where you render your `PreviewVideo` and `RemoteVideo` component? Following is my  implementation:
```
<StyledContent>
    <VideoTileGrid
      layout={
        layout === Layout.Gallery
          ? 'standard'
          : 'featured'
      }
      className="videos"
      // noRemoteVideoView={<MeetingDetails />}
    />
    <PreviewVideo />
    
    {mode === MeetingMode.Spectator ? (
      <DynamicMeetingControls />
    ) : (
      <MeetingControls />
    )}
</StyledContent>
```

**Comment by nainkunal933** [comment]
One of the issue that I noticed in an application like this is that `PreviewVideo` and `LocalVideo` have become tightly coupled over time and this can lead to undesirable side effects. If you want we can log this as a feature request to decouple the two components. In V3, we plan to make some changes to the Device Controller that might help with an implementation like this.

**Comment by LeviSklaroff** [comment]
Closing as there has been no response in over 30 days, if you would like to make this a feature request please feel free to reopen this issue.
