### ISSUE TITLE
Voice Focus is not initialized without passing CreatingMeetingResponse

### ISSUE THREAD

**Issue by ltrung** [aws/amazon-chime-sdk-component-library-react#784]
### What happened and what did you expect to happen?

In version 2.15, a new feature `Echo Reduction` is added to the library (See https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-chime-sdk-echo-reduction/ for more details). 
However, the change causes `VoiceFocusProvider` to only be initialized if `createMeetingResponse` is passed in. This should not be the case as `createMeetingResponse` is only needed to check for echo reduction feature.

Voice Focus is not initialized without passing `creatingMeetingResponse`.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

```
const App = () => (
  <VoiceFocusProvider>
    <MyChild />
  </VoiceFocusProvider>
);
```
Running the above code and Voice Focus is not initialized (`isVoiceFocusSupported` is undefined).

### Amazon Chime SDK React Components Library version

2.15.0

### What browsers are you seeing the problem on?

Any browsers that supports Voice Focus

### Browser version

N/A

### Device Information

N/A

### Meeting and Attendee ID Information.

N/A

### Browser console logs

N/A

### Add any other context about the problem here.

For now, you can workaround this by passing `createMeetingResponse` parameter or just a dummy object as below
```
const vfConfigValue = {
  spec: {name: 'default'},
  createMeetingResponse: { Meeting: {} }
};

const App = () => (
  <VoiceFocusProvider {...vfConfigValue}>
    <MyChild />
  </VoiceFocusProvider>
);
```

**Comment by wchmzn** [comment]
Thanks for the contact and context. 

Delay initialization after receiving CreatingMeetingResponse is inevitable for VoiceFocusProvider because we don't want to download model multiple times which potentially will be detrimental to the browser. So whether to download Voice Focus or Echo Reduction model is determined by CreatingMeetingResponse. On the other hand, Voice focus model and feature should be only legally used within meeting for free, so it is reasonable to have CreatingMeetingResponse which means the user is inside Meeting. Please find more in [Notices](https://static.sdkassets.chime.aws/workers/NOTICES.txt). Customers who wants to use Voice Focus outside meetings will be extra changed, such as our Voice Focus on AMI offering. 

Agree that the documentation could be improved so it will be helpful for customers with better implementation experience. Will follow up with a PR on that.

**Comment by wchmzn** [comment]
https://github.com/aws/amazon-chime-sdk-component-library-react/pull/800
