### ISSUE TITLE
Creating a dummy meeting

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-component-library-react#794]
### What are you trying to do?

*For example: I'm trying to run the demo app.*

I'm trying to create a dummy meeting, keep the selected device states and use this information in an actual meeting without leaving the dummy meeting. Leaving the dummy meeting would reset selected device states due to `meetingManager.leave()`.

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure a component.*

Is there any documentation indicating whether there are any potential memory leaks without calling `meetingManager.leave()` before joining a new meeting that hasn't been started with `meetingManager.start()`?

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime Component Library Guide, etc.

Amazon Chime Component Library Guide

**Comment by devalevenkatesh** [comment]
Thanks for reporting this issue.

The [`meetingManager.leave`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/providers/MeetingProvider/MeetingManager.ts#L199-L225) actually is responsible to stop the `meetingSession` and clean-up the attached audio-video input device streams. So, for cleanup to happen clearly suggest to use `meetingManager.leave`. You can use the MeetingStatus to know the meeting leave status and then create a new meeting as explained in [this](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/793#issuecomment-1109870711) issue. Since, we now with v3 destroy the `DeviceController` responsible to manage the devices, I think not doing so may lead to media stream issues as well as memory leaks.

**Comment by michhyun1** [comment]
@Nanosync I see there has been no response - please let us know if you still have questions. Will close this issue.
